
import './Privacy.css'
import { useEffect } from "react";
import Footer from '../../Components/Footer';

function ScrollToTopOnMount() {
    useEffect(() => {
        window.scrollTo(0, 0);
    }, []);

    return null;
}
export default function Privacy_policy() {
    return (
        <div>
            <ScrollToTopOnMount />

            <section className="section privacy__policy p-8 md:p-0">
                <div className="container privacy__policy-container">

                    <h1 className='mt-32 texts-dark'>Privacy Policy</h1>
                    <p>We takes your privacy seriously. This privacy policy talks about what personal information we collect and how we use it. See this privacy policy first to learn more about privacy policies in general.</p>

                    <div className="privacy__policy-content">
                        <h2>Information Collection</h2>
                        <p>Web servers track their visitor’s basic information. This information includes, but is not limited to, IP addresses, browser details, timestamps and referring pages. None of this information can personally identify specific visitors to this site. The information is tracked for routine administration and maintenance purposes.</p>


                        <h2>Cookies and Web Beacons</h2>
                        <p>Where it is necessary, (Web Address) uses cookies to store information about a visitor’s preferences and history in order to better serve the visitor and/or present the visitor with customized content.
                            <br />Advertising partners and other third parties may also use cookies, scripts and/or web beacons to track visitors to our site in order to display advertisements and other useful information. Such tracking is done directly by the third parties through their own servers and is subject to their own privacy policies.

                        </p>


                        <h2>Controlling Your Privacy</h2>
                        <p>Note that you can change your browser settings to disable cookies if you have privacy concerns. Disabling cookies for all sites is not recommended as it may interfere with your use of some sites. The best option is to disable or enable cookies on a per-site basis. Consult your browser documentation for instructions on how to block cookies and other tracking mechanisms. This list of web browser privacy management links may also be useful.
                        </p>

                        <h2>Contact Information</h2>
                        <p>Concerns or questions about this privacy policy can be directed to our Support for further clarification.
                            <br />This privacy policy was generated by the Privacy Policy for WordPress plugin.
                            <br /><br />
                            <strong>Privacy Policy for Breedss</strong>

                            <br />
                            The privacy of our visitors to Breedss is important to us.
                            <br />
                            <br />
                            We recognize that privacy of your personal information is important. Here is information on what types of personal information we receive and collect when you use and visit Breedss and how we safeguard your information.  We never sell your personal information to third parties.
                            <br />
                            <br />
                            <strong>Log Files</strong>

                            <br />
                            As with most other websites, we collect and use the data contained in log files.  The information in the log files include  your IP (internet protocol) address, your ISP (internet service provider, such as AOL or Shaw Cable), the browser you used to visit our site (such as Internet Explorer or Firefox), the time you visited our site and which pages you visited throughout our site.
                            <br />
                            <br />
                            <strong>Cookies and Web Beacons</strong>

                            <br />
                            We do use cookies to store information, such as your personal preferences when you visit our site.  This could include only showing you a popup once in your visit, or the ability to login to some of our features, such as forums.
                            <br />
                            <br />
                            We also use third party advertisements to support our site.  Some of these advertisers may use technology such as cookies and web beacons when they advertise on our site, which will also send these advertisers (such as Google through the Google AdSense program) information including your IP address, your ISP , the browser you used to visit our site, and in some cases, whether you have Flash installed.  This is generally used for geotargeting purposes (showing New York real estate ads to someone in New York, for example) or showing certain ads based on specific sites visited (such as showing cooking ads to someone who frequents cooking sites).
                            <br />
                            <strong>DoubleClick DART cookies</strong>

                            <br />
                            <br />
                            We also may use DART cookies for ad serving through Google’s DoubleClick, which places a cookie on your computer when you are browsing the web and visit a site using DoubleClick advertising (including some Google AdSense advertisements).  This cookie is used to serve ads specific to you and your interests (” interest-based targeting”).  The ads served will be targeted based on your previous browsing history (For example, if you have been viewing sites about visiting Las Vegas, you may see Las Vegas hotel advertisements when viewing a non-related site, such as on a site about hockey).  DART uses “non personally identifiable information”.  It does NOT track personal information about you, such as your name, email address, physical address, telephone number, social security numbers, bank account numbers or credit card numbers.  You can opt-out of this ad serving on all sites using this advertising by visiting &nbsp;
                            <a href="http://www.doubleclick.com/privacy/dart_adserving.aspx">Here</a>
                            <br />
                            <br />
                            You can choose to disable or selectively turn off our cookies or third-party cookies in your browser settings, or by managing preferences in programs such as Norton Internet Security.  However, this can affect how you are able to interact with our site as well as other websites.  This could include the inability to login to services or programs, such as logging into forums or accounts.
                            <br />
                            <br />
                            Deleting cookies does not mean you are permanently opted out of any advertising program.  Unless you have settings that disallow cookies, the next time you visit a site running the advertisements, a new cookie will be added.
                            <br />
                            <br />

                        </p>


                    </div>
                </div>
            </section>

            <Footer/>
        </div>
    )
}
